trigger: none

pool:
  vmImage: 'windows-latest'

variables:
  ResourceGroupName: 'rfc-e2e-software-survey'
  AppServiceName: 'NOT SET'
  AppDropFolder: 'app'
  E2ETestDropFolder: 'e2etest'
  E2ETARGET: 'NOT SET'
  'SoftwareSurvey:CosmosDbEndpoint': 'NOT SET'
  'SoftwareSurvey:Persistance:CosmosDbPrimaryKey': 'NOT SET'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'Create E2E Infrastructure'
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Red Folder Staging(276e2abc-6a34-4925-b24f-73913402ea4a)'
    subscriptionId: '276e2abc-6a34-4925-b24f-73913402ea4a'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(ResourceGroupName)'
    location: 'North Europe'
    templateLocation: 'Linked artifact'
    csmFile: 'Infrastructure/SoftwareSurveyInfrastructure.json'
    deploymentMode: 'Complete'
    deploymentOutputs: 'DeploymentOutputs'

- task: PowerShell@2
  displayName: 'Extract variables from E2E Infrastructure'
  inputs:
    targetType: 'inline'
    script: |
      $deploymentOutputs=ConvertFrom-Json '$(DeploymentOutputs)'

      # Used for the App Deployment
      $appServiceName = $deploymentOutputs.appServiceName.value
      Write-Host "##vso[task.setvariable variable=AppServiceName;]$appServiceName"

      #Used for the E2E Tests
      $e2eTarget = $deploymentOutputs.appServiceUrl.value
      $cosmosEndpoint = $deploymentOutputs.cosmosEndpoint.value
      $cosmosPrimaryKey = $deploymentOutputs.cosmosPrimaryKey.value
      Write-Host "##vso[task.setvariable variable=E2ETARGET;]$e2eTarget"
      Write-Host "##vso[task.setvariable variable='SoftwareSurvey:CosmosDbEndpoint';]$cosmoEndpoint"
      Write-Host "##vso[task.setvariable variable='SoftwareSurvey:Persistance:CosmosDbPrimaryKey';]$cosmosPrimaryKey"
      
      dir env:

- task: PowerShell@2
  displayName: 'Temp'
  inputs:
    targetType: 'inline'
    script: |
      dir env:

- task: DownloadBuildArtifacts@0
  displayName: 'Download the App'
  inputs:
    buildType: 'specific'
    project: '9edc70a4-66ef-45a6-b8c7-40c42a429065'
    pipeline: '22'
    buildVersionToDownload: 'latest'
    artifactName: 'drop'
    downloadType: 'single'
    downloadPath: '$(AppDropFolder)'

- task: AzureRmWebAppDeployment@4
  displayName: 'Deploy App to E2E Infrastructure'
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Red Folder Staging(276e2abc-6a34-4925-b24f-73913402ea4a)'
    appType: 'webApp'
    WebAppName: $(AppServiceName)
    packageForLinux: '$(AppDropFolder)/**/*.zip'

- task: DownloadBuildArtifacts@0
  displayName: 'Download the E2E tests'
  inputs:
    buildType: 'specific'
    project: '9edc70a4-66ef-45a6-b8c7-40c42a429065'
    pipeline: '22'
    buildVersionToDownload: 'latest'
    artifactName: 'test_drop'
    downloadType: 'single'
    downloadPath: '$(E2ETestDropFolder)'

- task: PowerShell@2
  displayName: 'Adds ChromeWebDriver for Selenium to PATH'
  inputs:
    targetType: 'inline'
    script: 'echo "##vso[task.prependpath]$env:CHROMEWEBDRIVER"'

- task: VSTest@2
  displayName: 'Run E2E Tests'
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\*.E2ETests.dll
      !**\*TestAdapter.dll
      !**\obj\**
    searchFolder: '$(E2ETestDropFolder)'
    uiTests: true