pool:
  vmImage: 'windows-latest'

variables:
  ResourceGroupName: 'rfc-e2e-software-survey'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Red Folder Staging(276e2abc-6a34-4925-b24f-73913402ea4a)'
    subscriptionId: '276e2abc-6a34-4925-b24f-73913402ea4a'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(ResourceGroupName)'
    location: 'North Europe'
    templateLocation: 'Linked artifact'
    csmFile: 'Infrastructure/SoftwareSurveyInfrastructure.json'
    deploymentMode: 'Complete'
    deploymentOutputs: 'DeploymentOutputs'



