trigger: none

pool:
  vmImage: 'windows-latest'

variables:
  ResourceGroupName: 'rfc-e2e-software-survey'
  AppServiceName: 'NOT SET'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Red Folder Staging(276e2abc-6a34-4925-b24f-73913402ea4a)'
    subscriptionId: '276e2abc-6a34-4925-b24f-73913402ea4a'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(ResourceGroupName)'
    location: 'North Europe'
    templateLocation: 'Linked artifact'
    csmFile: 'Infrastructure/SoftwareSurveyInfrastructure.json'
    deploymentMode: 'Complete'
    deploymentOutputs: 'DeploymentOutputs'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $deploymentOutputs=ConvertFrom-Json '$(DeploymentOutputs)'
      $appServiceName=$deploymentOutputs.appServiceName.value
      Write-Host "##vso[task.setvariable variable=AppServiceName;]$appServiceName".

- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'specific'
    project: '9edc70a4-66ef-45a6-b8c7-40c42a429065'
    definition: '22'
    buildVersionToDownload: 'latest'
    targetPath: '$(Pipeline.Workspace)'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Red Folder Staging(276e2abc-6a34-4925-b24f-73913402ea4a)'
    appType: 'webAppLinux'
    WebAppName: '$(AppServiceName)'
    packageForLinux: '$(Pipeline.Workspace)/**/*.zip'

