# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  displayName: 'Nuget Restore'
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  displayName: 'Build app'
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\SoftwareSurvey\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  displayName: 'Run unit tests'
  inputs:
    testAssemblyVer2: |
     **\$(BuildConfiguration)\*.UnitTests.dll
     **\$(BuildConfiguration)\**\*.UnitTests.dll
     !**\obj\**
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    codeCoverageEnabled: True
    otherConsoleOptions: '/platform:x64 /Framework:.NETCoreApp,Version=v3.1 /logger:console;verbosity="normal" '


- task: PublishBuildArtifacts@1
  displayName: 'Publish app'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)\SoftwareSurvey'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: AzureRmWebAppDeployment@4
  displayName: 'Deploy app to Azure App'
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Red Folder Production (20366cfc-092d-46d6-a630-a687d3a04992)'
    appType: 'webApp'
    WebAppName: 'rfc-software-survey'
    packageForLinux: '$(System.ArtifactStagingDirectory)/SoftwareSurvey/**/*.zip'

- task: CopyFiles@2
  displayName: 'Copy the E2E tests'
  inputs:
    Contents: |
      SoftwareSurvey.E2ETests\bin\$(BuildConfiguration)\**
      !**\chromedriver.exe
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish the E2E tests'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)\SoftwareSurvey.E2ETests\bin\$(BuildConfiguration)'
    ArtifactName: 'test_drop'
    publishLocation: 'Container'